### ISSUE TITLE
4.- Actividad principal: Listview con issues

### ISSUE THREAD

**Issue by MikeSagnelli** [MikeSagnelli/JUISMI#6]

**Comment by IsmaLga** [comment]
Subí a mi feature/ListView una versión que muestra en un Listview las taras. Por tarea se muestra un Tag (representado con un cuadro de color), nombre de la tarea, status, y un número de comentarios. Junto al número de comentarios debería de haber un ícono de comentarios, sigo trabajando en agregarlo. 

![](https://files.slack.com/files-tmb/T0TCS6PJP-F9C3U9SB0-0f143fc828/screenshot_20180219-082056_1024.png)

**Comment by IsmaLga** [comment]
Hay problema con añadir un botón de add issue, al parecer es algo con el RelativeLayout pero no estoy seguro. Lo seguiré checando.
